project:
  type: website
  output-dir: docs
website:
  title: "L'Å’uvre"
  #title: "Oeuvre"
  #site-url: "http://localhost:3221/"
  site-url: "fortunewalla.net"
  favicon: favicon.png
  google-analytics: "G-T2KJQMELJT"
  
  navbar:
    right:
      - text: " "
        icon: question-circle
        href: about.qmd
      - icon: rss
        href: index.xml
      #- icon: github
      #  href: https://github.com/
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



